deband=no
interpolation=no
hwdec-codecs=all
vo=gpu
gpu-api=vulkan
hwdec=auto-safe
cscale=bicubic
dscale=mitchell
scale=ewa_lanczos
video-sync=display-resample
no-sub
autofit-larger=960x540
ontop

osd-font='SF Pro'
