deband=no
interpolation=no
hwdec-codecs=all
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe
cscale=bicubic
dscale=mitchell
scale=ewa_lanczos
# If high-resolution videos drop frames, change to: scale=spline36

no-sub
autofit-larger=960x540
ontop

osd-font='SF Pro'

ytdl-format=bestvideo[vcodec!=?av1]+bestaudio/best
