#! /bin/sh

bspc monitor -d   3 4 5 6 7 8 9 10

# containers and placement
bspc config border_width                        3
bspc config window_gap                          14
bspc config split_ratio                         0.50
bspc config borderless_monocle                  true
bspc config gapless_monocle                     false
bspc config paddingless_monocle                 false
bspc config single_monocle                      false
bspc config top_padding                         14
bspc config right_padding                       0
bspc config bottom_padding                      14
bspc config left_padding                        0
bspc config auto_alternate                      false
bspc config auto_cancel                         true
# bspc config initial_polarity first_child

# focus
bspc config history_aware_focus                 true
bspc config focus_by_distance                   true
bspc config pointer_follows_monitor             true
bspc config pointer_follows_focus               false
bspc config focus_follows_pointer               true

# colors
bspc config focused_border_color                "#383838"
bspc config normal_border_color                 "#383838"
bspc config active_border_color                 "#383838"
bspc config focused_locked_border_color         "#383838"
bspc config normal_locked_border_color          "#383838"
bspc config active_locked_border_color          "#383838"
bspc config urgent_border_color                 "#ac4142"
bspc config presel_border_color                 "#6a9fb5"
bspc config presel_feedback_color               "#6a9fb5"
bspc config focused_private_border_color        "#383838"
bspc config active_private_border_color         "#383838"
bspc config normal_private_border_color         "#383838"

# window rules
# remove all rules first
bspc rule -r *:*

bspc rule -a mpv state=floating border=off
bspc rule -a feh state=floating border=off
bspc rule -a chromium state=monocle
bspc rule -a Hangouts state=floating


# wallpaper
if [ -s "$HOME/.fehbg" ]; then
  source "$HOME/.fehbg" 2>/dev/null
elif [ -e "$HOME/Pictures/background.png" ]; then
  feh --bg-scale --image-bg -B black "$HOME/Pictures/background.png"
fi

# startup
sxhkd &
$HOME/.config/polybar/launch.sh &
#$HOME/.config/bsp_lemonbar/bsp_lemonbar.sh &
thunar --daemon &
urxvtd -q -o -f &
dunst -c ~/.config/dunst/dunstrc &
xss-lock lockscreen &
sleep 0.5;xset s activate &
