#!/usr/bin/env bash
set -Eeuo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
HOME_MANIFEST="$REPO_DIR/manifests/home.txt"
SUGGESTED_MANIFEST="$REPO_DIR/manifests/suggested.txt"
ADOPT_SUGGESTED=0
CAPTURE_PACKAGES=1
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage: ./backup.sh [options]

Back up managed dotfiles from $HOME into this repository.

Options:
  --adopt-suggested  Also copy existing paths in manifests/suggested.txt and
                     append them to manifests/home.txt so install.sh manages them.
  --no-packages      Do not refresh pacman explicit package snapshots.
  --dry-run          Show what would change without writing files.
  -h, --help         Show this help.
USAGE
}

log()  { printf '[backup] %s\n' "$*"; }
warn() { printf '[backup] warning: %s\n' "$*" >&2; }

while (($#)); do
  case "$1" in
    --adopt-suggested) ADOPT_SUGGESTED=1 ;;
    --no-packages) CAPTURE_PACKAGES=0 ;;
    --dry-run) DRY_RUN=1 ;;
    -h|--help) usage; exit 0 ;;
    *) warn "unknown option: $1"; usage >&2; exit 2 ;;
  esac
  shift
done

[[ -f "$HOME_MANIFEST" ]] || { warn "missing $HOME_MANIFEST"; exit 1; }

manifest_paths() {
  local file=$1 line
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -n "$line" ]] && printf '%s\n' "$line"
  done < "$file"
}

same_target() {
  local a=$1 b=$2 ar br
  [[ -e "$a" || -L "$a" ]] || return 1
  [[ -e "$b" || -L "$b" ]] || return 1
  ar="$(realpath -m -- "$a")"
  br="$(realpath -m -- "$b")"
  [[ "$ar" == "$br" ]]
}

clean_runtime_state() {
  local dst=$1
  [[ -e "$dst" || -L "$dst" ]] || return 0
  find "$dst" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
  find "$dst" -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete 2>/dev/null || true
  case "$dst" in
    */.config/ranger)
      rm -f "$dst/history" "$dst/tagged"
      ;;
    */.config/systemd)
      find "$dst/user" -maxdepth 1 -type d -name '*.target.wants' -prune -exec rm -rf {} + 2>/dev/null || true
      ;;
  esac
}

backup_path() {
  local rel=$1 src="$HOME/$rel" dst="$REPO_DIR/home/$rel"

  if [[ ! -e "$src" && ! -L "$src" ]]; then
    warn "not found, skipping: ~/$rel"
    return 1
  fi

  if same_target "$src" "$dst"; then
    log "already live from repo: ~/$rel"
    return 0
  fi

  if ((DRY_RUN)); then
    log "would copy ~/$rel -> home/$rel"
    return 0
  fi

  mkdir -p -- "$(dirname -- "$dst")"
  if [[ -d "$src" ]]; then
    mkdir -p -- "$dst"
    rsync -a --delete --exclude='__pycache__/' --exclude='*.pyc' --exclude='*.pyo' \
      -- "$src/" "$dst/"
  else
    rm -rf -- "$dst"
    cp -aL -- "$src" "$dst"
  fi
  clean_runtime_state "$dst"
  log "updated: home/$rel"
}

append_managed_path() {
  local rel=$1
  grep -Fxq -- "$rel" "$HOME_MANIFEST" && return 0
  if ((DRY_RUN)); then
    log "would add to manifest: $rel"
  else
    printf '%s\n' "$rel" >> "$HOME_MANIFEST"
    log "adopted into manifest: $rel"
  fi
}

while IFS= read -r rel; do
  backup_path "$rel" || true
done < <(manifest_paths "$HOME_MANIFEST")

if ((ADOPT_SUGGESTED)); then
  log "adopting suggested paths that currently exist"
  while IFS= read -r rel; do
    if [[ -e "$HOME/$rel" || -L "$HOME/$rel" ]]; then
      if backup_path "$rel"; then
        append_managed_path "$rel"
      fi
    else
      log "suggested path absent, leaving untracked: ~/$rel"
    fi
  done < <(manifest_paths "$SUGGESTED_MANIFEST")
fi

if ((CAPTURE_PACKAGES)); then
  if command -v pacman >/dev/null 2>&1; then
    if ((DRY_RUN)); then
      log "would refresh packages/explicit-native.txt and packages/explicit-foreign.txt"
    else
      {
        printf '# Generated by ./backup.sh from pacman -Qqen\n'
        pacman -Qqen
      } > "$REPO_DIR/packages/explicit-native.txt"
      {
        printf '# Generated by ./backup.sh from pacman -Qqem\n'
        pacman -Qqem
      } > "$REPO_DIR/packages/explicit-foreign.txt"
      log "refreshed explicit package snapshots"
    fi
  else
    warn "pacman not found; package snapshots were not refreshed"
  fi
fi

if command -v git >/dev/null 2>&1 && git -C "$REPO_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  printf '\n'
  git -C "$REPO_DIR" status --short
fi
