#!/bin/bash
TMPBG=/tmp/screen.png
LOCK=$HOME/.config/lockscreen/lock.png
RES=1600x900

ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "smartblur=5:1,hue=s=0.5,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $TMPBG
i3lock -n -u -i $TMPBG
rm $TMPBG
