# Theme: mine
# By: Ron Asimi

# Main bg
theme[main_bg]="#272727"

# Main text color
theme[main_fg]="#c3c3c3"

# Title color for boxes
theme[title]="#c3c3c3"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ac4142"

# Background color of selected item in processes box
theme[selected_bg]="#5d5d5d"

# Foreground color of selected item in processes box
theme[selected_fg]="#c3c3c3"

# Color of inactive/disabled text
theme[inactive_fg]="#5d5d5d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#75b5aa"

# Cpu box outline color
theme[cpu_box]="#5d5d5d"

# Memory/disks box outline color
theme[mem_box]="#5d5d5d"

# Net up/down box outline color
theme[net_box]="#5d5d5d"

# Processes box outline color
theme[proc_box]="#5d5d5d"

# Box divider line and small boxes line color
theme[div_line]="#5d5d5d"

# Temperature graph colors
theme[temp_start]="#90a959"
theme[temp_mid]="#f4bf75"
theme[temp_end]="#ac4142"

# CPU graph colors
theme[cpu_start]="#8ab4f8"
theme[cpu_mid]="#f4bf75"
theme[cpu_end]="#ac4142"

# Mem/Disk free meter
theme[free_start]="#8ab4f8"
theme[free_mid]="#f4bf75"
theme[free_end]="#ac4142"

# Mem/Disk cached meter
theme[cached_start]="#8ab4f8"
theme[cached_mid]="#f4bf75"
theme[cached_end]="#ac4142"

# Mem/Disk available meter
theme[available_start]="#8ab4f8"
theme[available_mid]="#f4bf75"
theme[available_end]="#ac4142"

# Mem/Disk used meter
theme[used_start]="#8ab4f8"
theme[used_mid]="#f4bf75"
theme[used_end]="#ac4142"

# Download graph colors
theme[download_start]="#8ab4f8"
theme[download_mid]="#f4bf75"
theme[download_end]="#ac4142"

# Upload graph colors
theme[upload_start]="#8ab4f8"
theme[upload_mid]="#f4bf75"
theme[upload_end]="#ac4142"
