#!\bin\bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"

geometry="1568x16+16+8"
font="-*-tamzenforpowerline-medium-r-*-*-14-*-*-*-*-*-*-*"
iconfont="Material Design Icons:size=10"
clickables=16
res_w=$(xrandr | grep "current" | awk '{print $8a}')

# Alarm settings
cpu_alert=75				# % cpu use
bat_alert=5				# low battery %
temp_alert=90				# high temp

# update timers, in minutes (conky update in i3_lemonbar_conky)
mail_timer=5				# Mail check timer (min)
upd_timer=30				# Update check (min)

# get colors from .Xresources
fg=$(xrdb -query | grep 'foreground'| cut -f2 | sed -e "s/#//")
bg=$(xrdb -query | grep 'background'| cut -f2 | sed -e "s/#//")
black=$(xrdb -query | grep 'color0'| cut -f2 | sed -e "s/#//")
red=$(xrdb -query | grep 'color1'| cut -f2 | sed -e "s/#//")
green=$(xrdb -query | grep 'color2'| cut -f2 | sed -e "s/#//")
yellow=$(xrdb -query | grep 'color3'| cut -f2 | sed -e "s/#//")
blue=$(xrdb -query | grep 'color4'| cut -f2 | sed -e "s/#//")
magenta=$(xrdb -query | grep 'color5'| cut -f2 | sed -e "s/#//")
cyan=$(xrdb -query | grep 'color6'| cut -f2 | sed -e "s/#//")
white=$(xrdb -query | grep 'color7'| cut -f2 | sed -e "s/#//")

# bar color definitions
color_back="#C0${bg}"			# Default background
color_fore="#${fg}"			# Default foreground
color_title="#FFFFFFFF"			# Window title foreground
color_head="#C0${blue}"			# Background for first element
color_wsp="#${black}"			# Background for selected workspace
color_act="#${fg}"		        # Foreground for active workspace
color_ina="#${black}"		        # Foreground for inactive workspace
color_sec_b1="#C0282828"		# Background for section 1
color_sec_b2="#C0${bg}"			# Background for section 2
color_icon="#${fg}"  			# For icons
color_icon_dark="#FF282828"		# For icons (dark)
color_netdown="#C0${black}"		# For inactive network interface icons
color_mail="#C0DD4B39"			# Background color for mail alert
color_upd="#C01793D0"			# Background color for update alert
color_alert="#C0${red}"			# Background color for  alert

#default space between sections
if [ "${res_w}" -gt 1024 ]; then
        stab='  '
else
        stab=' '
fi

# Char glyps for powerline fonts
sep_left=""				# Powerline separator left
sep_right=""				# Powerline separator right

# Icon glyphs from Material Icons
icon_clock="肋"				# Clock icon
icon_cal=""				# Calendar icon
icon_ethup=""				# Ethernet up icon
icon_ethdown=""			# Ethernet down icon
icon_wifi_up=""			# Wifi up icon
icon_wifi_down=""			# Wifi down icon
icon_mail=""				# Mail icon
icon_arch=""				# Arch icon

icon_bright_100=""			# Full brightness icon
icon_bright_80=""			# 80% brightness icon
icon_bright_51=""			# 51% brightness icon
icon_bright_31=""			# 31% brightness icon
icon_bright_19=""			# 19% brightness icon
icon_bright_11=""			# 11% brightness icon
icon_bright_6=""			# <6% brightness icon

icon_vol_hi=""			# Full brightness icon
icon_vol_med=""         		# 80% brightness icon
icon_vol_lo=""		               	# 51% brightness icon
icon_vol_off=""			        # 31% brightness icon
icon_vol_mute=""         		# 19% brightness icon

icon_bat_charge=""			# On charger icon
icon_bat_full=""			# Full battery icon
icon_bat_90=""				# 90% battery icon
icon_bat_80=""				# 80% battery icon
icon_bat_70=""				# 70% battery icon
icon_bat_60=""				# 60% battery icon
icon_bat_50=""				# 50% battery icon
icon_bat_40=""				# 40% battery icon
icon_bat_30=""				# 30% battery icon
icon_bat_20=""				# 20% battery icon
icon_bat_10=""				# 10% battery icon
icon_bat_0=""				# 0% battery icon
icon_bat_low=""				# Low battery icon
