[main]
font=SF Pro:size=10
prompt="Search: "
icons-enabled=no

# Dimensions calculated for exactly 25% coverage on a 1080p display
# Note: If you still need to lower the font size further (e.g., size=9), 
# you will need to increase width and lines to maintain the same footprint.
width=110
lines=17
anchor=center
x-margin=0
y-margin=0

# Internal margins (padding) in pixels
horizontal-pad=20
vertical-pad=20
# Internal spacing between individual list items
inner-pad=6
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=1d1d1d61
text=c3c3c3ff
match=8ab4f8ff
selection=8ab4f8ff
selection-text=272727ff
border=1d1d1dff

[border]
width=1
radius=9
