#!\bin\bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="1572x14+14+7"
font="-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-*-1"
iconfont="Material Design Icons:size=9"
res_w=$(xrandr | grep "current" | awk '{print $8a}')
snd_cha=$(amixer get Master | grep "Playback channels:" | awk '{if ($4 == "") {printf "%s: Playback", $3} else {printf "%s %s: Playback", $3, $4}}')

# Alarm settings
cpu_alert=75				# % cpu use
bat_alert=5				# low battery %
temp_alert=90				# high temp

# update timers, in minutes (conky update in i3_lemonbar_conky)
mail_timer=5				# Mail check timer (min)
upd_timer=30				# Update check (min)

# color definitions
color_back="#C02F343F"			# Default background
color_fore="#C0EAEAEB"			# Default foreground
color_title="#FFFFFFFF"			# Window title foreground
color_head="#C06A9FB5"			# Background for first element
color_sec_b1="#C0171A1F"		# Background for section 1
color_sec_b2="#C02F343F"		# Background for section 2
color_sec_b3="#C060676E"		# Background for section 3
color_icon="#FFEAEAEB"			# For icons
color_icon_dark="#FF2F343F"		# For icons (dark)
color_netdown="#C08C8C8D"		# For inactive network interface icons
color_mail="#C0DD4B39"			# Background color for mail alert
color_upd="#C01793D0"			# Background color for update alert
color_alert="#C0AC4142"			# Background color for cpu/temp/memory alert
color_wsp="#C090A959"			# Background for selected workspace
color_ina="#FF434852"		        # Foreground for inactive workspace
color_urg="#FFAC4142"                   # Foreground for urgent workspace
color_cal="#C090A959"			# Background for calendar
color_bat="#C0AC4142"			# Background for battery

#default space between sections
if [ ${res_w} -gt 1024 ]; then
  stab='  '
else
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""				# Powerline separator left
sep_right=""				# Powerline separator right
sep_l_left=""				# Powerline light separator left
sep_l_right=""				# Powerline light separator right

# Icon glyphs from Material Icons
icon_clock=""				# Clock icon
icon_cal=""				# Calendar icon
icon_cpu=""				# CPU icon
icon_mem=""				# MEM icon
icon_ethup=""				# Ethernet up icon
icon_ethdown=""			# Ethernet down icon
icon_wifi_up=""			# Wifi up icon
icon_wifi_down=""			# Wifi down icon
icon_tether_up=""			# Tether up icon
icon_tether_down=""			# Tether down icon
icon_mail=""				# Mail icon
icon_arch=""				# Arch icon
icon_prog=""				# Window icon
icon_wsp=""				# Workspace icon
icon_temp=""				# Temp icon
icon_bright=""				# Brightness icon

icon_charge=""				# On charger icon
icon_full=""				# Full battery icon
icon_90=""				# 90% battery icon
icon_80=""				# 80% battery icon
icon_70=""				# 70% battery icon
icon_60=""				# 60% battery icon
icon_50=""				# 50% battery icon
icon_40=""				# 40% battery icon
icon_30=""				# 30% battery icon
icon_20=""				# 20% battery icon
icon_10=""				# 10% battery icon
icon_0=""				# 0% battery icon
icon_low=""				# Low battery icon
