--enable-features=WaylandWindowDecorations
--ozone-platform-hint=wayland
--disable-features=WaylandOverlayDelegation
--enable-features=WebRTCPipeWireCapturer
--password-store=gnome-libsecret
--disable-font-subpixel-positioning
--disable-lcd-text
