Net/ThemeName "Materia-dark-compact"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "OpenZone_White_Slim"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
