[General]
user_name = Ron Asimi
default_location = London, Ontario
text_model = phi4-mini
vision_model = moondream
max_history = 6
notif_id = 9999

[Paths]
history_file = ~/.local/share/ai-assist-history.json
kb_file = ~/.local/share/ai-assist-kb.txt
alba_path = ~/.bin/alba-say

[Credentials]
gmail_user = ron.asimi@gmail.com
gmail_pass = xpjl gswg ylop kdrn
calendar_url = https://calendar.google.com/calendar/ical/ron.asimi%40gmail.com/private-1e9d8c301385f504d080075c62969e85/basic.ics
