#!/bin/sh

mount /mnt/btrfs_vol
 
dest=/mnt/btrfs_vol

day=$( date +'%m-%d-%Y-%H:%M:%S')
 
echo "taking root filesystem snapshot..."
 
# The command
btrfs subvolume snapshot / $dest/_root-$day

umount /mnt/btrfs_vol

