#!/bin/sh

mount /.snapshots
 
dest=/.snapshots

day=$( date +'%m-%d-%Y-%H:%M:%S')
 
echo "taking root filesystem snapshot..."
 
# The command
btrfs subvolume snapshot / $dest/@root-$day

umount /.snapshots

