#!/bin/sh

cd ~ || return

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Disable HiDPI scaling
#export WINIT_HIDPI_FACTOR=1.0
#export WINIT_X11_SCALE_FACTOR=1.0

# Enable trash-cli for electron apps
export ELECTRON_TRASH=trash-cli

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=OpenZone_White_Slim

# Set a cursor size
export XCURSOR_SIZE=16

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# Set GTK backend
#export GDK_BACKEND=wayland

# Set QT theme
export QT_QPA_PLATFORMTHEME=qt6ct

# Set Libreoffice to use GTK for wayland
export SAL_USE_VCLPLUGIN=gtk3

# Firefox flags
#export MOZ_DISABLE_RDD_SANDBOX=1
#export MOZ_X11_EGL=1
export MOZ_USE_XINPUT2=1
export MOZ_ENABLE_WAYLAND=1

# Testing using .xinitrc syntax
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
systemctl --user import-environment DISPLAY &
gsettings set org.gnome.desktop.interface gtk-theme 'Materia-dark-compact' &
gsettings set org.gnome.desktop.interface gtk-application-prefer-dark-theme 'true' &

exec Hyprland
