#!/bin/sh

cd ~

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=OpenZone_White_Slim

# Set a cursor size
export XCURSOR_SIZE=16

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# Set GTK backend
GDK_BACKEND=wayland

# Testing using .xinitrc syntax
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
systemctl --user import-environment DISPLAY &
gsettings set org.gnome.desktop.interface gtk-theme 'Materia-dark-compact' &
gsettings set org.gnome.desktop.interface gtk-application-prefer-dark-theme 'true' &

exec Hyprland
