#!/bin/bash
# i3 panel config. Powerline style.
# Ron Asimi
# _                            _                _
#| | ___ _ __ ___   ___  _ __ | |__   __ _ _ __| |
#| |/ _ \ '_ ` _ \ / _ \| '_ \| '_ \ / _` | '__| |
#| |  __/ | | | | | (_) | | | | |_) | (_| | |  |_|
#|_|\___|_| |_| |_|\___/|_| |_|_.__/ \__,_|_|  (_)
#

# initialize the pipe
panel_fifo="/tmp/i3_lemonbar_${USER}"

# lemonbar settings
geometry="1600x20"
font="Source Code Pro:style=SemiBold:size=10.5"
plfont="-*-tamzenforpowerline-medium-r-*-*-20-*-*-*-*-*-*-*"
iconfont="Material Design Icons:style:Regular:size=9"
clickables=64
res_w=$(xrandr | grep "current" | awk '{print $8a}')

# alarm settings
bat_alert=5  # low battery %

# update timers, in minutes
mail_timer=5 # Mail check timer (min)
upd_timer=30 # Update check (min)

# grab colors from Xresources
fgd=$(xrdb -query | grep '*.foreground:' | cut -f 2 | tr -d "#")
bgd=$(xrdb -query | grep '*.background:' | cut -f 2 | tr -d "#")
bla=$(xrdb -query | grep '*.color0:' | cut -f 2 | tr -d "#")
bbla=$(xrdb -query | grep '*.color8:' | cut -f 2 | tr -d "#")
red=$(xrdb -query | grep '*.color1:' | cut -f 2 | tr -d "#")
bred=$(xrdb -query | grep '*.color9:' | cut -f 2 | tr -d "#")
grn=$(xrdb -query | grep '*.color2:' | cut -f 2 | tr -d "#")
bgrn=$(xrdb -query | grep '*.color10:' | cut -f 2 | tr -d "#")
ylw=$(xrdb -query | grep '*.color3:' | cut -f 2 | tr -d "#")
bylw=$(xrdb -query | grep '*.color11:' | cut -f 2 | tr -d "#")
blu=$(xrdb -query | grep '*.color4:' | cut -f 2 | tr -d "#")
bblu=$(xrdb -query | grep '*.color12:' | cut -f 2 | tr -d "#")
mgt=$(xrdb -query | grep '*.color5:' | cut -f 2 | tr -d "#")
bmgt=$(xrdb -query | grep '*.color13:' | cut -f 2 | tr -d "#")
cya=$(xrdb -query | grep '*.color6:' | cut -f 2 | tr -d "#")
bcya=$(xrdb -query | grep '*.color14:' | cut -f 2 | tr -d "#")
whi=$(xrdb -query | grep '*.color7:' | cut -f 2 | tr -d "#")
bwhi=$(xrdb -query | grep '*.color15:' | cut -f 2 | tr -d "#")

# bar color definitions
color_back="#E6${bgd}"    # Default background
color_fore="#${fgd}"      # Default foreground
color_title="#${bwhi}"    # Window title foreground
color_stat="#${bla}"      # Background for i3 status section
color_ina="#${blu}"       # Background for inactive workspace
color_wsp="#${bblu}"      # Background for selected workspace
color_act_fore="#181818"  # Foreground for active workspace
color_ina_fore="#${bla}"  # Foreground for inactive workspace
color_sec_b1="#181818"    # Background for section 1
color_sec_b2="#${bgd}"    # Background for section 2
color_icon="#${whi}"      # For icons
color_icon_dark="#212121" # For icons (dark)
color_netdown="#${bla}"   # For inactive network interface icons
color_mail="#DD4B39"      # Color for mail alert
color_upd="#1793D0"       # Color for update alert
color_warn="#${ylw}"      # Color for warning
color_alert="#${red}"     # Color for alert
color_mode="#${bred}"     # Foreground color for binding mode

#default space between sections
if [ "${res_w}" -gt 1024 ]; then
  stab='  '
else
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""        # Powerline separator left
sep_right=""       # Powerline separator right

# Icon glyphs from Material Design Icons
icon_cal="󰃶"        # Calendar icon
icon_clock="󰅐"      # Clock icon
icon_ethup="󰈁"      # Ethernet up icon
icon_ethdown="󰈂"    # Ethernet down icon
icon_wifi_up="󰤨"    # Wifi up icon
icon_wifi_down="󰤮"  # Wifi down icon
icon_mail="󰊫"       # Mail icon
icon_arch="󰣇"       # Arch icon

icon_default="󰌌"    # default mode icon
icon_resize="󰩨"     # resize mode icon

icon_splith="󰜨"     # horizontal split layout icon
icon_splitv="󰜩"     # vertical split icon
icon_tabbed="󰓩"     # tabbed layout icon
icon_stacked="󰯋"    # stacked layout icon

icon_vol_boost="󰕾"  # Boosted volume icon
icon_vol_hi="󰕾"     # High volume icon
icon_vol_med="󰖀"    # Medium volume icon
icon_vol_lo="󰕿"     # Low volume icon
icon_vol_off="󰸈"    # Volume off icon
icon_vol_mute="󰝟"   # Mute icon

icon_bright_100="󰃠" # Full brightness icon
icon_bright_80="󰃟"  # 80% brightness icon
icon_bright_51="󰃞"  # 51% brightness icon
icon_bright_31="󰃝"  # 31% brightness icon
icon_bright_19="󰃜"  # 19% brightness icon
icon_bright_11="󰃛"  # 11% brightness icon
icon_bright_6="󰃚"   # <6% brightness icon

icon_bat_ac="󰚥"     # On charger icon
icon_bat_charge="󰂄" # Battery charging icon
icon_bat_full="󰁹"   # Full battery icon
icon_bat_90="󰂂"     # 90% battery icon
icon_bat_80="󰂁"     # 80% battery icon
icon_bat_70="󰂀"     # 70% battery icon
icon_bat_60="󰁿"     # 60% battery icon
icon_bat_50="󰁾"     # 50% battery icon
icon_bat_40="󰁽"     # 40% battery icon
icon_bat_30="󰁼"     # 30% battery icon
icon_bat_20="󰁻"     # 20% battery icon
icon_bat_10="󰁺"     # 10% battery icon
icon_bat_0="󰂃"      # 0% battery icon
icon_bat_low="󰂃"    # Low battery icon
