[main]
position=top
orientation=v
width=200
height=200
icon-size=72
show-percentage=false
margins=440 0 0 0
timeout=3
transition-time=250
listeners=audio_in,audio_out,backlight
backlight-path=
keyboard-path=
