[main]
position=top-right
orientation=h
width=270
height=36
icon-size=22
show-percentage=true
margins=36 0 0 0
timeout=3
transition-time=250
listeners=audio_in,audio_out,backlight
backlight-path=
keyboard-path=
