directory: /mnt/storage/music
library: /mnt/storage/music/musiclibrary.db

import:
    move: yes

plugins: fetchart lastgenre embedart acousticbrainz

fetchart:
    auto:  yes

lastgenre:
    auto:  yes

embedart:
    auto:  yes
    remove_art_file:  yes

acousticbrainz:
    auto:  yes
