exec-once = [silent] hyprpm reload -nn
exec-once = [silent] ~/.config/waybar/waybar.sh
exec-once = [silent] hyprpaper
exec-once = [silent] dunst
exec-once = [workspace 3 silent] thunar --daemon
exec-once = [silent] hypridle
exec-once = [silent] wl-clip-persist --clipboard regular
exec-once = [silent] wl-paste --watch cliphist store
exec-once = [silent] /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = [silent] dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = [silent] gsettings set org.gnome.desktop.interface cursor-size 24