exec-once = [silent] dbus-update-activation-environment --systemd --all
exec-once = [silent] systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = [silent] /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = [silent] eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
exec-once = [silent] dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = [silent] gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors-light'
exec-once = [silent] gsettings set org.gnome.desktop.interface cursor-size 24
exec-once = [silent] gsettings set org.gnome.desktop.interface gtk-theme 'Materia-dark-compact'
exec-once = [silent] gsettings set org.gnome.desktop.interface gtk-application-prefer-dark-theme 'true'exec-once = [silent] hyprpm reload
exec-once = [silent] hypridle
exec-once = [silent] dunst
exec-once = [silent] wl-clip-persist --clipboard regular
exec-once = [silent] wl-paste --watch cliphist store
exec-once = [workspace 3 silent] thunar --daemon
exec-once = [silent] hyprpaper
exec-once = [silent] ~/.config/waybar/waybar.sh
exec-once = [silent] nm-applet 
exec-once = [silent] blueberry-tray