
preload = /home/ron/Pictures/Wallpapers/Master Unknown/master-unknown-cK4azpU71BE-unsplash.jpg
wallpaper =,/home/ron/Pictures/Wallpapers/Master Unknown/master-unknown-cK4azpU71BE-unsplash.jpg
splash = false
ipc = off
