general {
    ignore_dbus_inhibit = true
    
    # Prevent multiple instances of the lock script
    lock_cmd = flock -n /tmp/hyprlock.lock -c 'pidof hyprlock || ($HOME/.config/hypr/scripts/media_pause.sh & hyprlock --immediate-render)'
    
    # Restore display state
    on_unlock_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    
    before_sleep_cmd = loginctl lock-session
    
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 300                                                                         
    on-timeout = $HOME/.config/hypr/scripts/media_pause.sh & loginctl lock-session            
}

listener {
    timeout = 330                                                                         
    # Turn off display
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
