
preload = /home/ron/Pictures/Wallpapers/Master Unknown/master-unknown-1jNkFjn7aec-unsplash.jpg
wallpaper =,/home/ron/Pictures/Wallpapers/Master Unknown/master-unknown-1jNkFjn7aec-unsplash.jpg
splash = false
ipc = off
