general {
    lock_cmd = pidof hyprlock || (~/.config/hypr/scripts/media_pause.sh & uwsm app -- hyprlock --immediate-render)
    on_unlock_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'             # turn on display after the lock screen app exits
    before_sleep_cmd = sleep 0.5 && loginctl lock-session                      # pause media and lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'               # to avoid having to press a key twice to turn on the display.
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener { 
    timeout = 300                                          # 5min.
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0 # turn off keyboard backlight.
    on-resume = brightnessctl -rd tpacpi::kbd_backlight        # turn on keyboard backlight.
}

listener {
    timeout = 300                                                                         # 5min
    on-timeout = ~/.config/hypr/scripts/media_pause.sh & loginctl lock-session            # pause media and lock screen when timeout has passed
}

listener {
    timeout = 330                                                                                  # 5.5min
    on-timeout = brightnessctl -s && sleep 0.5 && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                 # save backlight state, wait for screenshot, then screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired, then restore backlight.
}